name: bump_build
description: A dev dependency for helping the creation of Android and iOS releases.
version: 0.0.1
homepage: https://github.com/mludovico/bump_build

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
